### ISSUE TITLE
Subfinder crashes when run against only a TLD 

### ISSUE THREAD

**Issue by thefawsec** [projectdiscovery/subfinder#333] opened 2020-09-27 02:59 UTC
**Description of bug**
When the tool is used against just a tld like `.gov or .mil` etc, with the `-all` flag, it crashes.
Please note that the issue exist when using `-all` flag otherwise it is working perfectly without using `-all` flag.

**Subfinder version that I am using**
v2.4.5

**To reproduce this, enter following command**
`subfinder -d mil -all
`

**Screenshot**
![Screenshot from 2020-09-27 07-54-00](https://user-images.githubusercontent.com/71954201/94354645-bcf1f500-0096-11eb-9b47-f8655b378baa.png)

**Comment by vzamanillo** [comment] 2020-09-27 11:22
Hey! thank you for reporting.

I am not able to reproduce this with the latest master branch, could you please provide us some extended info (verbose output, complete command... etc) to catch this?

**Comment by thefawsec** [comment] 2020-09-27 14:01
Well I am running the same command again as i mentioned above, and it is working fine now!
About 13 hours ago i tried `subfinder -d mil -all` thrice but it kept on crashing after running for a few seconds.
anyways, i just ran it twice and its working properly now.

**Comment by bauthard** [comment] 2020-09-27 14:36
We will try to see what's going on, but querying TLD is not expected and we do not suggest to use in that way, on a quick look we found `crtsh` and `bufferover` support this query, so you might to run `subfinder -d mil -sources crtsh,bufferover` instead of using `-all` @thefawsec

**Comment by thefawsec** [comment] 2020-09-27 16:42
okay. Thanks for the quick response guys.

**Comment by bauthard** [comment] 2020-12-02 07:37
Closing this out as this is not a feature or expected way to run subfinder, no changes required on this.

**Closed by bauthard** 2020-12-02 07:37 UTC
