### ISSUE TITLE
Results cannot be saved to a single file.

### ISSUE THREAD

**Issue by ZeroDot1** [projectdiscovery/subfinder#199] opened 2019-12-10 12:00 UTC
## What's the problem (or question)?
I want to save all subdomains found in a single file not for each domain a file.
Unfortunately this is not possible.

## How can we reproduce the issue?
`$ cat 'URLsToScan1.txt' | '/bin/subfinder' -silent -oD /Dokumente/URLsToScanDONESF.txt`

**Comment by ZeroDot1** [comment] 2019-12-10 12:16
And I see some error messages:
```bash
[WRN] Could not run source urlscan: Fail to get result query: Fail to unmarshal urlscan.io get result: json: cannot unmarshal number into Go struct field .meta.processors.wappa.data.categories.priority of type string
[WRN] Could not run source ipv4info: Could not get ip tokens
```

**Comment by Ice3man543** [comment] 2019-12-10 13:21
Hey @ZeroDot1,

Regarding error messages, let's detail each one of those - 

1. `[WRN] Could not run source digicert: Get https://ssltools.digicert.com/chainTester/webservice/ctsearch/search?keyword=0769.it: net/http: request canceled (Client.Timeout exceeded while awaiting headers)` -> This one is regarding a timeout with digicert not being reachable. Can you do a curl to the site. It seems sometimes digicert is not responding. The best way would be leave this as is. Though i could probably add a flag for warnings.

2. `[WRN] Could not run source ipv4info: Could not get ip tokens` -> This error occurs when there is no result for a domain. I'll be removing this error to not show anything in case no result were found. Would that be enough?

3. `[WRN] Could not run source urlscan: Fail to get result query: Fail to unmarshal urlscan.io get result: json: cannot unmarshal number into Go struct field .meta.processors.wappa.data.categories.priority of type string` -> This one is interesting. I'll try to fix this and see the root cause.

Regarding saving results in a single file, i'll add that ASAP.

Thanks!

**Comment by ZeroDot1** [comment] 2019-12-10 17:23
digicert.com often doesn't answer because my internet connection is too slow. 

ipv4info, Yeah, that's okay. 

Thank you very much for your work, I appreciate it very much, keep up the good work.

**Comment by bauthard** [comment] 2019-12-18 06:43
Hi @ZeroDot1, 

The aim of saving results to each file to make it more manageable for the user, for your use case you can simply run the **subfinder** in following way to get the expected results. 


```
cat 'URLsToScan1.txt' | '/bin/subfinder' -silent | tee URLsToScanDONESF.txt
```

For having results in both way, you can simply do, `cat *.txt > URLsToScanDONESF.txt` in the results directory.

**Comment by ZeroDot1** [comment] 2019-12-18 11:13
Hi @bauthard,
Thanks for the tip. 
I use it now in the following way:
`cat 'URLsToScan.txt' | 'bin/subfinder' -silent -oD /folder/ | tee /URLsToScanDONESF.txt`
First all URLs are written to individual files, and at the same time all URLs are written to a single file. 
This makes it easier for me to filter out URLs.

CC: @Ice3man543

**Comment by manuelbua** [comment] 2019-12-28 17:11
@bauthard why did you close this issue?

As there is no way to disable output file creation when multiple domains are specified, what are the options now? Sure we can pipe everything to `tee` but i still don't want it to litter my directories with tens of files for the sake of it.

My opinion is that if the user explicitly supplies an output file, then it can be used, else it shouldn't create them on its own.

**Comment by bauthard** [comment] 2019-12-30 11:30
@manuelbua, 

Valid point, will reopen this issue to support `-o` flag in case of multiple domains.

**Comment by Ice3man543** [comment] 2020-01-10 10:25
HI @manuelbua @ZeroDot1 results can now be saved to a single file while using the -o flag with the output file name in case of domain list.  Just do -

```bash
./subfinder -dL list.txt -o output-file.txt
```

**Comment by bauthard** [comment] 2020-01-10 11:33
@ZeroDot1, 

Single file issue got fixed at https://github.com/projectdiscovery/subfinder/pull/211. 

```
[WRN] Could not run source urlscan: Fail to get result query: Fail to unmarshal urlscan.io get result: json: cannot unmarshal number into Go struct field .meta.processors.wappa.data.categories.priority of type string
[WRN] Could not run source ipv4info: Could not get ip tokens
[WRN] Could not run source digicert: Get https://ssltools.digicert.com/chainTester/webservice/ctsearch/search?keyword=0769.it: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

These warning messages indicate that subfinder unable to connect the sources due to rate limit implementation at other end so this can not be fixed from our side.

**Closed by bauthard** 2020-01-10 11:33 UTC
Labels: enhancement
