### ISSUE TITLE
[Issue] SIGSEGV when using the -all option

### ISSUE THREAD

**Issue by xqd-ai** [projectdiscovery/subfinder#351] opened 2020-12-10 11:51 UTC
**Describe the bug**
application crash when using the -all option

**Subfinder version**
v2.4.5

**Complete command you used to reproduce this**
subfinder -d uber.com  -all -o subdomains-uber.txt

```
____  _| |__ / _(_)_ _  __| |___ _ _
(_-< || | '_ \  _| | ' \/ _  / -_) '_|
/__/\_,_|_.__/_| |_|_||_\__,_\___|_| v2.4.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] By using subfinder, you also agree to the terms of the APIs used.

[INF] Enumerating subdomains for uber.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7b89b0]

goroutine 55 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*agent).enumerate(0xc00018e0c0, 0xa2fae0, 0xc0000209c0, 0xc000192090, 0x30)
        /home/marco/go/src/github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:40 +0x190
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run.func1(0xc00018e0c0, 0xa2fae0, 0xc0000209c0, 0x7ffd19ff2276, 0x8)
        /home/marco/go/src/github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:73 +0xc2
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run
        /home/marco/go/src/github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:72 +0xc0

```

**Screenshots**
Add screenshots of the error for a better context.

**Comment by team-projectdiscovery** [comment] 2020-12-10 13:13
Hi @xqd-ai, 

Closing as this is a duplicate of https://github.com/projectdiscovery/subfinder/issues/347, temporary solution, run subfinder with `subfinder -exclude-sources sitedossier -all`

**Closed by team-projectdiscovery** 2020-12-10 13:13 UTC
